# Generated by Django 4.2.30 on 2026-06-21 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=300, verbose_name='标题(EN)')),
                ('title_jp', models.CharField(blank=True, max_length=300, verbose_name='标题(JP)')),
                ('summary_en', models.TextField(verbose_name='摘要(EN)')),
                ('summary_jp', models.TextField(blank=True, verbose_name='摘要(JP)')),
                ('content_en', models.TextField(blank=True, verbose_name='内容(EN)')),
                ('content_jp', models.TextField(blank=True, verbose_name='内容(JP)')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='分类')),
                ('is_published', models.BooleanField(default=False, verbose_name='发布')),
                ('published_at', models.DateField(blank=True, null=True, verbose_name='发布日期')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '博客管理',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='公司名称')),
                ('contact_person', models.CharField(max_length=100, verbose_name='联系人')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='电话/WhatsApp')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='国家')),
                ('market', models.CharField(choices=[('usa', 'USA'), ('japan', 'Japan'), ('other', 'Other')], default='usa', max_length=20, verbose_name='目标市场')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('source', models.CharField(blank=True, max_length=100, verbose_name='来源')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户管理',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(blank=True, max_length=100, verbose_name='需求量')),
                ('target_price', models.CharField(blank=True, max_length=100, verbose_name='目标价')),
                ('delivery_location', models.CharField(blank=True, max_length=200, verbose_name='交货地')),
                ('message', models.TextField(verbose_name='询价内容')),
                ('status', models.CharField(choices=[('new', 'New / 新询价'), ('quoted', 'Quoted / 已报价'), ('negotiating', 'Negotiating / 洽谈中'), ('converted', 'Converted / 已转订单'), ('closed', 'Closed / 已关闭')], default='new', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='trading.customer', verbose_name='客户')),
            ],
            options={
                'verbose_name': '询价',
                'verbose_name_plural': '询价管理',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=200, verbose_name='名称(EN)')),
                ('name_jp', models.CharField(blank=True, max_length=200, verbose_name='名称(JP)')),
                ('name_cn', models.CharField(blank=True, max_length=200, verbose_name='名称(CN)')),
                ('category', models.CharField(choices=[('bar', 'Silver Bar / 银锭'), ('grain', 'Silver Grain / 银粒'), ('powder', 'Silver Powder / 银粉')], max_length=20, verbose_name='分类')),
                ('purity', models.CharField(max_length=50, verbose_name='纯度')),
                ('specs', models.TextField(blank=True, verbose_name='规格')),
                ('description_en', models.TextField(verbose_name='描述(EN)')),
                ('description_jp', models.TextField(blank=True, verbose_name='描述(JP)')),
                ('moq', models.CharField(blank=True, max_length=100, verbose_name='最小起订量')),
                ('price_range', models.CharField(blank=True, max_length=200, verbose_name='价格区间')),
                ('is_active', models.BooleanField(default=True, verbose_name='上架')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品管理',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=50, unique=True, verbose_name='订单号')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='数量(kg)')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='单价(USD/kg)')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='总金额(USD)')),
                ('payment_term', models.CharField(choices=[('tt', 'TT / 电汇'), ('lc', 'LC / 信用证')], default='tt', max_length=20, verbose_name='支付方式')),
                ('delivery_term', models.CharField(default='FOB Hong Kong', max_length=100, verbose_name='交货条款')),
                ('delivery_port', models.CharField(blank=True, max_length=200, verbose_name='目的港')),
                ('shipping_method', models.CharField(blank=True, max_length=50, verbose_name='运输方式')),
                ('etd', models.DateField(blank=True, null=True, verbose_name='预计发货日')),
                ('eta', models.DateField(blank=True, null=True, verbose_name='预计到货日')),
                ('status', models.CharField(choices=[('pending', 'Pending / 待确认'), ('confirmed', 'Confirmed / 已确认'), ('paid', 'Paid / 已付款'), ('shipped', 'Shipped / 已发货'), ('delivered', 'Delivered / 已送达'), ('cancelled', 'Cancelled / 已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='trading.customer', verbose_name='客户')),
                ('inquiry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trading.inquiry', verbose_name='来源询价')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trading.product', verbose_name='产品')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单管理',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='inquiry',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trading.product', verbose_name='产品'),
        ),
    ]
